version: '3.7'

services:
  user.api:
    container_name: user.api
    image: ${REGISTRY:-rendify}/user.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./src/microservices/user
      dockerfile: Dockerfile
      args:
        - NODE_ENV=dev
    depends_on:
      - user-data
      - rabbit-rendify
    networks:
      - rendify-api-dev

  user-data:
    image: postgres:11.5
    networks:
      - rendify-api-dev
    container_name: user-data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user

  kong-rendify:
    image: ${REGISTRY:-rendify}/kong:${PLATFORM:-linux}-${TAG:-latest}
    container_name: kong-rendify
    build:
      context: ./src/gateways/kong
      dockerfile: Dockerfile
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:5001, 0.0.0.0:5444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:5000, 0.0.0.0:5443 ssl
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    networks:
      - kong-net
      - rendify-api-dev
    volumes:
      - kong_vol:/usr/local/kong/declarative
    ports:
      - "5000:5000/tcp"
      - "127.0.0.1:5001:5001/tcp"
      - "5443:5443/tcp"
      - "127.0.0.1:5444:5444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure

  rabbit-rendify:
    image: rabbitmq:3-management-alpine
    networks:
      - rendify-api-dev
    container_name: rabbit-rendify
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=Rabbit_123

networks:
  rendify-api-dev:
  kong-net:

volumes:
  kong_vol: {}
