version: '3.7'

services:
  user.api:
    container_name: user.api
    image: ${REGISTRY:-rendify}/user.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./src/microservices/user
      dockerfile: Dockerfile
      args:
        - NODE_ENV=dev
    depends_on:
      - user-data
      - rabbit-rendify
    networks:
      - rendify-api-dev

  user-data:
    image: postgres:11.5
    networks:
      - rendify-api-dev
    container_name: user-data
    volumes:
      - user_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user
      - PGDATA=/var/lib/postgresql/data/pgdata

  kong-rendify:
    image: ${REGISTRY:-rendify}/kong:${PLATFORM:-linux}-${TAG:-latest}
    container_name: kong-rendify
    build:
      context: ./src/gateways/kong
      dockerfile: Dockerfile
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:5001, 0.0.0.0:5444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:5000, 0.0.0.0:5443 ssl
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    networks:
      - kong-net
      - rendify-api-dev
    ports:
      - "5000:5000/tcp"
      - "127.0.0.1:5001:5001/tcp"
      - "5443:5443/tcp"
      - "127.0.0.1:5444:5444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure

  rabbit-rendify:
    image: rabbitmq:3-management-alpine
    networks:
      - rendify-api-dev
    container_name: rabbit-rendify
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=Rabbit_123

  keycloak-db:
    image: postgres:11.5
    container_name: keycloak-db
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - keycloak-net
    environment:
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - PGDATA=/var/lib/postgresql/data/pgdata

  keycloak:
    image: jboss/keycloak:10.0.2
    depends_on:
      - keycloak-db
    networks:
      - keycloak-net
    ports:
      - "8180:8080"
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=keycloak
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

networks:
  rendify-api-dev:
  keycloak-net:
  kong-net:

volumes:
  user_data: {}
  keycloak_data: {}
