version: '3.7'

services:
  user_api_dev:
    build:
      context: ./microservices/user
      dockerfile: Dockerfile
      args:
        - APP_ENV=dev
        - DB_SYNC=true
        - DB_URL=postgresql://postgres:postgres@postgres_dev:5432/user
    depends_on:
      - postgres_user
      - rabbit_dev
    ports:
      - "3001:3001"
    container_name: user_api_dev

  postgres_user:
    image: postgres:11.5
    container_name: postgres_user
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user

  rabbit_dev:
    image: rabbitmq:3
    container_name: rabbit_dev
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=Rabbit_123
