version: "3.7"
services:

  user-data:
    image: postgres:11.5
    container_name: user-data
    networks:
      - node-boilerplate-api
    ports:
      - "54321:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user

  kong:
    image: kong:2.2
    container_name: kong
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:5001, 0.0.0.0:5444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:5000, 0.0.0.0:5443 ssl
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    networks:
      - node-boilerplate-api
    ports:
      - "5000:5000/tcp"
      - "127.0.0.1:5001:5001/tcp"
      - "5443:5443/tcp"
      - "127.0.0.1:5444:5444/tcp"
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    volumes:
      - ./src/gateways/kong/kong.yml:/usr/local/kong/declarative/kong.yml

networks:
  node-boilerplate-api:

