export = [
  {
    environment: 'dev',
    name: 'dev',
    type: 'postgres',
    url: 'postgresql://postgres:postgres@user-data:5432/user',
    synchronize: 'true',
    logging: true,
    entities: ['src/models/**/*.ts'],
    migrations: ['src/migrations/**/*.ts'],
    subscribers: ['src/subscriber/**/*.ts'],
    cli: {
      entitiesDir: 'src/models',
      migrationsDir: 'src/migrations',
      subscribersDir: 'src/subscriber',
    },
    migrationsTableName: '_migration_table',
  },
  {
    environment: 'staging',
    name: 'staging',
    type: 'postgres',
    url: 'postgres://kleqlggk:XMMZZWS_9Ec4E1_3n9hNAxAn76MOJqxS@rogue.db.elephantsql.com:5432/kleqlggk',
    synchronize: 'true',
    logging: true,
    entities: ['src/models/**/*.ts'],
    migrations: ['src/migrations/**/*.ts'],
    subscribers: ['src/subscriber/**/*.ts'],
    cli: {
      entitiesDir: 'src/models',
      migrationsDir: 'src/migrations',
      subscribersDir: 'src/subscriber',
    },
    migrationsTableName: '_migration_table',
  },
  {
    environment: 'prod',
    name: 'prod',
    type: 'postgres',
    url: 'postgres://dadefinire',
    synchronize: 'false',
    logging: true,
    entities: ['src/models/**/*.ts'],
    migrations: ['src/migrations/**/*.ts'],
    subscribers: ['src/subscriber/**/*.ts'],
    cli: {
      entitiesDir: 'src/models',
      migrationsDir: 'src/migrations',
      subscribersDir: 'src/subscriber',
    },
    migrationsTableName: '_migration_table',
  },
];
