http:
  port: 5000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  user-api:
    host: localhost
    methods: "GET,POST,PUT,DELETE"
    paths: ["/user", "/user/*"]
serviceEndpoints:
  user:
    url: "http://localhost:3001"
policies:
  - proxy
pipelines:
  - name: user
    apiEndpoints:
      - user-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: user
              ignorePath:   true
