name: user.api

on:
  push:
    branches:
      - develop
    paths:
      - 'microservices/user/*'

jobs:
  checkError:
    name: Check Error
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'develop'
      #- name: Install yarn
      #  run: npm install -g yarn
      - name: Navigate to folder
        run: cd microservices/user
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn run lint
      #- name: Test
      #  run: yarn run test
      - name: Build local
        run: yarn run build
  pushImage:
    name: Build and publish docker image
    needs: checkError
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'develop'
      - name: Navigate to folder
        run: cd microservices/user
      - name: Install dependencies
        run: yarn
      - name: Build docker
        run: yarn run docker:build:staging