name: user.api-staging

on:
  push:
    branches:
      - develop
    paths:
      - 'microservices/user/**'

jobs:
  checkError:
    name: Check Error
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'develop'
      - name: Install dependencies
        run: |
          cd microservices/user
          yarn
      #- name: Test
      #  run: |
      #    cd microservices/user
      #    yarn run test
      - name: Build local
        run: |
          cd microservices/user
          yarn run build
  pushImage:
    name: Build and publish docker image
    needs: checkError
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'develop'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Create aws repo if not exist
        run: aws ecr describe-repositories --repository-names user.api-staging || aws ecr create-repository --repository-name user.api-staging --region eu-central-1
      - name: Build and push image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd microservices/user
          yarn run docker:build:staging
          docker push docker push $ECR_REGISTRY/user.api-staging:user_api
      